name: test
on: [push]
jobs:
  test-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./ # For real world usage this should be replaced by "antaljanosbenjamin/build-latex-with-make@master"
  test-directory:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./ # For real world usage this should be replaced by "antaljanosbenjamin/build-latex-with-make@master"
        with:
          directory: tests
